googleapis/google-http-java-client

google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpResponse.java, google-http-client/src/main/java/com/google/api/client/testing/http/javanet/MockHttpURLConnection.java, google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpResponseTest.java, google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpTransportTest.java, google-http-client/src/test/java/com/google/api/client/testing/http/javanet/MockHttpUrlConnectionTest.java
JDK's HttpUrlConnection implementation fails to notify clients when the
connection is lost when reading a response, e.g., the server gets restarted.
This changelist patches the NetHttpResponse to detect abrupt connection
termination when a fixed content length is available. In the case where
responses are chunk encoded, connection lost is well handled by JDK.
Also extend MockHttpUrlConnection for more testing functionalities.
=> Patch NetHttpResponse to detect abrupt termination

google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpRequest.java
There have been numerous reports of users of the client library seeing IO exceptions bearing the message "insufficient data written" (google/google-api-java-client#781 google/google-api-java-client#782 GoogleCloudPlatform/google-cloud-java#1018)
I believe these error messages are misleading, and are secondary effect of attempting to close the stream when the underlying IO operation was actually failing (see [underlying close implementation](https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L3187)) 
Therefore I propose we handle the case when there has been an underlying IO exception error, we still attempt to close the stream but let the original IO exception propagate nonetheless.
=> Swallow exception from close call when there is an underlying IOException

google-http-client-jackson/pom.xml, google-http-client/pom.xml
@garrettjonesgoogle @chanseokoh @ejona86 This patch adds OSGI metadata to the google-http-client jar.
=> add OSGI metadata to google-http-client

google-http-client/src/main/java/com/google/api/client/util/ArrayMap.java, google-http-client/src/test/java/com/google/api/client/util/ArrayMapTest.java
This should fix: https://github.com/google/google-http-java-client/issues/384
Just checking if the values are not null before calling the hash code method on them.
=> Fixing ArrayMap hashCode to work with null values

google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/util/OpenCensusUtils.java, google-http-client/src/test/java/com/google/api/client/util/OpenCensusUtilsTest.java
This PR adds [OpenCensus-Java](https://github.com/census-instrumentation/opencensus-java) instrumentation in to monitor and record events when executing `HttpExecute#execute()`.
The instrumentation starts a `Span` when the method begins, and is ended before the method exits. The status of the span will be determined according to the status of the response. This `Span` is stored into local span store, and can be optionally exported if user explicitly configure an exporter (e.g. [stackdriver exporter](https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/trace/stackdriver)).
`Span`s can have children. In this case, the generated `Span` in the instrumentation will be parent of all the `Span`s generated by server-side procedure. To link the children `Span` with their …
=> Add OpenCensus tracing instrumentation in google-http-client module.

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/util/OpenCensusUtils.java, google-http-client/src/test/java/com/google/api/client/util/OpenCensusUtilsTest.java
* Add method and instrumentation to record message events with content-length when sending/receiving
request/response.
* Refine API, add `volatile` modifiers to internal attributes.
* Use `registerSpanNamesForCollection` to replace `setSampleToLocalSpanStore`.
* Add get/set method for recordEvent so users can controll whether to expose collected spans.
* Add more tests and rewrite/fix test cases with JUnit 3 style.
* Fix/refine javadoc and messages.
I have done some basic integration test locally and fix some defects. Codes can be found [here](https://github.com/HailongWen/opencensus-java/blob/google-http-java-client-interop-testing/examples/src/test/java/io/opencensus/examples/trace/GoogleHttpJavaClientInteropTesting.java)
Please @mattwhisenhunt kindly help on merging this PR after …
=> Enhance OpenCensus tracing instrumentation.

google-http-client/src/main/java/com/google/api/client/http/HttpTransport.java
The example here:
https://developers.google.com/identity/sign-in/web/backend-auth
Shows:
new GoogleIdTokenVerifier.Builder(transport, jsonFactory)
But doesn't show where the transport or jsonFactory come from.
It was easy to find the right JSON library from the left-nav here:
https://developers.google.com/api-client-library/java/google-http-java-client/setup
But it was not so easy to find a HTTPTransport from that page or from the Javadoc here:
https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/http/HttpTransport.java
Both those sources suggested that plain old Java projects use com.google.api.client.javanet.NetHttpTransport which I could not find.  But com.google.api.client.googleapis.javanet.GoogleNetHttpTransport was …
=> Preferred implementation in comments was hard to find

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/http/OpenCensusUtils.java, google-http-client/src/test/java/com/google/api/client/http/OpenCensusUtilsTest.java
Resolves a circular dependency:
`utils.OpenCensusUtils` depends on `http.HttpHeaders`, `http.HttpHeaders` depends on `utils.*`.
The change is to move `utils.OpenCensusUtils` to `http.OpenCensusUtils`, which is not the greatest solution but should work.
Maven doesn't care but google's internal build tooling does care.
=> internal: resolve circular dependency

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java
This code does not compile internally.
Internal error: 
```
error: [MustBeClosedChecker] The result of this method must be closed.
Scope ws = tracer.withSpan(span);
```
=> supress MustBeClosed

google-http-client/pom.xml
This fixes a bug wherein the jarjar repackaging rules would incorrectly repackage the jar such that the packaged result is unusable, despite the non-packaged code and tests running fine.
=> fix pom to include correct guava version

pom.xml
This fixes a packaging problem described in https://github.com/google/google-http-java-client/pull/434. It is a cleaner fix than the fix applied in that PR.
=> bump jarjar plugin version

google-http-client/src/main/java/com/google/api/client/http/GenericUrl.java, google-http-client/src/main/java/com/google/api/client/http/HttpHeaders.java, google-http-client/src/main/java/com/google/api/client/http/HttpMediaType.java, google-http-client/src/main/java/com/google/api/client/testing/http/MockLowLevelHttpRequest.java, google-http-client/src/main/java/com/google/api/client/util/ClassInfo.java, google-http-client/src/main/java/com/google/api/client/util/DataMap.java, google-http-client/src/main/java/com/google/api/client/util/GenericData.java
The no-arg method uses Locale.getDefault() internally. On an Android device, this uses the currently active Locale. If the currently active locale happens to be Turkish, then uppercase "I" becomes a non-ASCII unicode character 'LATIN SMALL LETTER DOTLESS I'.
This specifically manifested as the header X-Goog-Encode-Response-If-Executable being rejected by the okhttp library because it contained the non-ASCII character.
NOTE: this commit was originally written by @stuartfehr
=> Fixed calls to toLowerCase() to be toLowerCase(Locale.US) instead.

google-http-client/src/main/java/com/google/api/client/http/GenericUrl.java
We'll start matching this with a new error-prone (https://github.com/google/error-prone) check soon otherwise: it looks like this is comparing two different getters.
=> Make GenericUrl's #equals pass static analysis

google-http-client/src/main/java/com/google/api/client/util/ArrayMap.java, google-http-client/src/test/java/com/google/api/client/util/ArrayMapTest.java
=> fix arraymap iterator remove issue

.kokoro/presubmit/java9.cfg, google-http-client-jdo/pom.xml, pom.xml
* Update datanucleus plugin versions to build on Java 9/10.
* Update clirr-maven-plugin to 2.8 to work on Java 10.
* Removing Java 9 from the test matrix as we cannot resolve the issue and guava does not seem to work on Java 9 anyways.
=> Fix compilation for Java 10

google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpResponseTest.java
throwIfFalseEOF method don't take into account bytes read/skipped in skip method and throws IOException when legit EOF was reached.
=> Fix throwIfFalseEOF if skip method was called before read

.gitignore, README.md, google-http-client-android/src/main/java/com/google/api/client/extensions/android/json/AndroidJsonFactory.java, google-http-client-android/src/main/java/com/google/api/client/extensions/android/json/AndroidJsonParser.java, google-http-client-appengine/pom.xml, google-http-client-appengine/src/main/java/com/google/api/client/extensions/appengine/http/UrlFetchTransport.java, google-http-client-appengine/src/main/java/com/google/api/client/extensions/appengine/http/package-info.java, google-http-client-assembly/dependencies/google-http-client-android-dependencies.html, google-http-client-assembly/dependencies/google-http-client-appengine-dependencies.html, google-http-client-assembly/dependencies/google-http-client-dependencies.html, google-http-client-assembly/dependencies/google-http-client-gson-dependencies.html, google-http-client-assembly/dependencies/google-http-client-jackson-dependencies.html, google-http-client-assembly/dependencies/google-http-client-jackson2-dependencies.html, google-http-client-assembly/dependencies/google-http-client-jdo-dependencies.html, google-http-client-assembly/dependencies/google-http-client-protobuf-dependencies.html, google-http-client-assembly/dependencies/google-http-client-xml-dependencies.html, google-http-client-assembly/readme.html, google-http-client-findbugs/src/main/resources/findbugs.xml, google-http-client-gson/src/main/java/com/google/api/client/json/gson/GsonFactory.java, google-http-client-gson/src/main/java/com/google/api/client/json/gson/GsonParser.java, google-http-client-gson/src/main/java/com/google/api/client/json/gson/package-info.java, google-http-client-protobuf/src/main/java/com/google/api/client/http/protobuf/package-info.java, google-http-client-protobuf/src/main/java/com/google/api/client/protobuf/package-info.java, google-http-client/src/main/java/com/google/api/client/json/JsonParser.java, google-http-client/src/test/java/com/google/api/client/http/UrlEncodedContentTest.java, instructions.html, pom.xml, samples/dailymotion-simple-cmdline-sample/instructions.html, samples/googleplus-simple-cmdline-sample/instructions.html, samples/googleplus-simple-cmdline-sample/src/main/java/com/google/api/services/samples/googleplus/cmdline/simple/GooglePlusSample.java
Fixes #468 (the few left are still working, and the others have nowhere to go right now - appengine-sdk code doesn't appear available on GitHub).
Fixes #469
=> Fix code.google.com links. Fix maven version

google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java, google-http-client/src/test/java/com/google/api/client/http/apache/ApacheHttpTransportTest.java
Adds support for HTTP PATCH method using the apache client.
=> add patch to google http client

google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java, google-http-client/src/test/java/com/google/api/client/http/apache/ApacheHttpTransportTest.java
This reverts commit 1f067daec8ab7871e9fce53398220e621c7642ae.
We need to revert this until we can upgrade Apache httpclient internally for android.
=> Revert "add patch to google http client (#486)"

google-http-client/pom.xml
Fixes #502)
There are some failing tests that don't seem related. Looking into those though:
Failed tests: 
```
HttpRequestTest.testExecute_curlLogger:1199 expected:<...P-Java-Client/1.26.0[-SNAPSHOT] (gzip)' -- 'http://...> but was:<...P-Java-Client/1.26.0[] (gzip)' -- 'http://...>
HttpRequestTest.testExecute_curlLoggerWithContentEncoding:1230 expected:<...P-Java-Client/1.26.0[-SNAPSHOT] (gzip)' -H 'Content...> but was:<...P-Java-Client/1.26.0[] (gzip)' -H 'Content...>
HttpRequestTest.testExecute_headerSerialization:961 expected:<[foo Google-HTTP-Java-Client/1.26.0-SNAPSHOT (gzip)]> but was:<[foo Google-HTTP-Java-Client/1.26.0 (gzip)]>
HttpRequestTest.testSuppressUserAgentSuffix:1111 expected:<...P-Java-Client/1.26.0[-SNAPSHOT] (gzip)> but was:<...P-Java-Client/1.26.0[] (gzip)> …
```
=> guava is not provided

clirr-ignored-differences.xml, google-http-client/src/main/java/com/google/api/client/http/BackOffPolicy.java, google-http-client/src/main/java/com/google/api/client/http/ExponentialBackOffPolicy.java, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/util/ExponentialBackOff.java, google-http-client/src/test/java/com/google/api/client/http/ExponentialBackOffPolicyTest.java, google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java
This reverts commit d5effe81f5cb627d458929819914abf10086821a.
This feature is still being used by google-api-java-client's batchRequest feature and needs to be removed from there first.
=> Revert "Remove deprecated BackOffPolicy interface (#506)"

.kokoro/release/stage.sh, google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-jdo/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/http/LowLevelHttpRequest.java, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, samples/googleplus-simple-cmdline-sample/pom.xml, versions.txt
11-09-2018 09:27 PST
- Allow Enums in DataMaps ([#505](https://github.com/googleapis/google-http-java-client/pull/505))
- Add write timeout for post/put requests ([#485](https://github.com/googleapis/google-http-java-client/pull/485))
- Add google-http-client-bom artifact ([#517](https://github.com/googleapis/google-http-java-client/pull/517))
- guava is not a regular dependency ([#508](https://github.com/googleapis/google-http-java-client/pull/508))
- Upgrade maven-javadoc-plugin to 3.0.1 ([#519](https://github.com/googleapis/google-http-java-client/pull/519))
- Set the version of the jarjar-maven-plugin in pluginManagement ([#515](https://github.com/googleapis/google-http-java-client/pull/515))
- Fix parameter of maven-javadoc-plugin …
=> Release google-http-java-client v1.27.0

google-http-client/src/main/java/com/google/api/client/http/AbstractHttpContent.java
Fixes #300 Request charset defaults to UTF-8, Response charset defaults to ISO_8859_1
=> Fix default charset for HttpRequest

google-http-client/src/main/java/com/google/api/client/util/Data.java
Fixes #273 
This PR makes signature of com.google.api.client.util.Data#nullOf more type safe so that it fails compile time check when somebody tries to use as ```Double obj = Data.nullOf(Integer.class);```
=> Make signature of com.google.api.client.util.Data#nullOf more type safe

google-http-client/src/main/java/com/google/api/client/util/FieldInfo.java, google-http-client/src/test/java/com/google/api/client/util/GenericDataTest.java
Fixes #340
Update put to use setter if defined with matching parameter
=> Httpheaders put use setter if defined

google-http-client/src/main/java/com/google/api/client/http/UriTemplate.java, google-http-client/src/test/java/com/google/api/client/http/UriTemplateTest.java
Fixes #351  UriTemplate.expand does not properly escape characters for path-style parameter expansion
=> Fix UriTemplate.expand to properly escape value

google-http-client/src/main/java/com/google/api/client/http/HttpResponseException.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseExceptionTest.java
Fixes #323 IllegalCharsetNameException in HttpResponse getContentCharset() if charset is malformed
=> Fix to build HttpResponseException when charset is malformed

google-http-client/src/main/java/com/google/api/client/json/JsonGenerator.java, google-http-client/src/main/java/com/google/api/client/json/JsonParser.java
Fixes #342 JsonGenerator and JsonParser should implement Closeable (and Flushable)
=> Implement Closeable & Flushable in JsonGenerator and JsonParser

google-http-client-android/pom.xml, google-http-client-appengine/pom.xml, google-http-client-findbugs/google-http-client-findbugs-test/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-jdo/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml
We're dropping Java 6 in the next release, so set the maven-compiler to use source level 1.7 and to compile to 1.7 binary. Also update animal-sniffer-plugin to java17 to allow 1.7 source.
=> Compile to Java 1.7 binary

google-http-client-jackson/src/main/java/com/google/api/client/json/jackson/JacksonFactory.java, google-http-client-jackson/src/main/java/com/google/api/client/json/jackson/JacksonGenerator.java, google-http-client-jackson/src/main/java/com/google/api/client/json/jackson/JacksonParser.java, google-http-client-jackson/src/main/java/com/google/api/client/json/jackson/package-info.java
=> Deprecate google-http-client-jackson

google-http-client-android/src/main/java/com/google/api/client/extensions/android/http/AndroidHttp.java
This is a beta API that should no longer be necessary. Gingerbread is no longer supported by Google Play Services so this could only be useful for someone building an extremely legacy app (and they would need to use an earlier version anyways).
=> Deprecate AndroidHttp compatibility shim

google-http-client/src/main/java/com/google/api/client/testing/util/MockBackOff.java
Fixes `MockBackOff#getMaxTries` which should return `maxTries` (instead of `numTries`)
=> Fixed MockBackOff#getMaxTries, returns `maxTries`

google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/util/OpenCensusUtils.java, google-http-client/src/test/java/com/google/api/client/util/OpenCensusUtilsTest.java, pom.xml
=> Re-add OpenCensus integration

google-http-client/pom.xml
Fixes https://github.com/googleapis/google-api-java-client/issues/1220
=> Fix commons-codec shading

pom.xml
Fixes warning about trying to set maven version in `<prerequisites>` tag.
=> Use maven enforcer plugin for maven version requirements

google-http-client/src/main/java/com/google/api/client/util/OpenCensusUtils.java, google-http-client/src/test/java/com/google/api/client/util/OpenCensusUtilsTest.java
Also fixes the `@since` tag as this is just now being introduced (not in 1.24)
=> Update OpenCensus deprecations

google-http-client-gson/src/test/java/com/google/api/client/json/gson/GsonGeneratorTest.java, google-http-client-jackson/src/test/java/com/google/api/client/json/jackson/JacksonGeneratorTest.java, google-http-client-jackson2/src/test/java/com/google/api/client/json/jackson2/JacksonGeneratorTest.java, google-http-client-test/src/main/java/com/google/api/client/test/json/AbstractJsonGeneratorTest.java, google-http-client/src/main/java/com/google/api/client/json/JsonGenerator.java
From #404 
If a map is iterable, then the JSON generator treats the map as an array when it should still be treated as a JSON object.
=> Fix iterable maps JSON serialization

.kokoro/release/drop.sh, .kokoro/release/promote.sh
Allows use to use the drop/promote Kokoro jobs by providing the STAGING_REPOSITORY_ID via environment variable
=> Provide STAGING_REPOSITORY_ID as an environment variable

google-http-client-assembly/pom.xml, google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/util/Base64.java, google-http-client/src/main/java/com/google/api/client/util/StringUtils.java, google-http-client/src/test/java/com/google/api/client/util/StringUtilsTest.java, pom.xml
Fixes #457 
Use guava Base64 handling until we drop Java 7 support and can use the built-in classes.
Use Java 7 charset handling for StringUtils.
By removing commons-codec, we should no longer need to jarjar a shaded version of commons-codec (and guava). We can also remove the antrun plugin which scrubbed the shaded commons-codec. This will also unblock the windows tests in #562 (file permissions errors during antrun plugin) Edit: it unblocked it, but there are more failures.
=> Remove commons-codec dependency

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/http/OpenCensusUtils.java, google-http-client/src/test/java/com/google/api/client/http/OpenCensusUtilsTest.java
Avoid circular dependency between packages.
Also makes the class default visibility as it's an internal class. This should be fine because it hasn't been released yet.
=> Move OpenCensusUtils to com.google.api.client.http

google-http-client/src/main/java/com/google/api/client/http/OpenCensusUtils.java
Users need the ability to configure the propagation format and other configs.
=> OpenCensusUtils does need to be public

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-legacy/pom.xml, google-http-client-apache/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-jdo/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
01-10-2019 10:14 PST
- Java 6 support was dropped - ([#542](https://github.com/googleapis/google-http-java-client/pull/542))
- The Apache HttpClient adapter was extracted out of the primary `google-http-client` artifact into the `google-http-client-apache` artifact with 2 separate versions ([#543](https://github.com/googleapis/google-http-java-client/pull/543)):
- Version 1.28.0 uses the exact same interface that was extracted from `google-http-client` and lives under the `google-http-client-apache-legacy/` directory
- Version 2.0.0 uses a simplified version of the code (breaking changes included), but allows you to actually use a modern version of Apache's HttpClient.
- Allow users to override handleResponse on …
=> Release google-http-java-client v1.28.0

google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpRequest.java, google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpRequestTest.java
Fixes #530 
cc @dzelemba
It's possible that a server handling a POST/PUT with content will interrupt the write and return a response. If this is the case, we should be able to read the response rather than throwing an IOException.
=> Fix handling interrupted uploads

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java
=> 372: Changed SingleThreadExecutor to FixedThreadPool(1).

google-http-client/src/main/java/com/google/api/client/util/GenericData.java, google-http-client/src/test/java/com/google/api/client/json/GenericJsonTest.java, google-http-client/src/test/java/com/google/api/client/util/GenericDataTest.java
Fixes [#936](https://github.com/googleapis/google-api-java-client/issues/936)
- [ X] Tests pass
=> Implement equals and Hashcode on GenericData

google-http-client/pom.xml
depend directly on Apache httpclient instead of pulling it in transitively from weird android dependency.
Not sure why tests didn't run, but there's a local failure I'm investigating.
OK.  tests passed locally. First failure was probably a DNS glitch caused by putting laptop to sleep in the middle. 
@sduskis I'm still concerned that the kokoro jobs didn't fire here.
=> depend directly on Apache httpclient

google-http-client-assembly/readme.html
=> remove Java 5 reference

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-legacy/pom.xml, google-http-client-apache/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
02-25-2019 10:57 PST
- Implement equals and Hashcode on GenericData ([#589](https://github.com/googleapis/google-http-java-client/pull/589))
- 372: Changed SingleThreadExecutor to FixedThreadPool(1). ([#588](https://github.com/googleapis/google-http-java-client/pull/588))
- Add option to return raw stream from response ([#579](https://github.com/googleapis/google-http-java-client/pull/579))
- Fix handling interrupted uploads ([#572](https://github.com/googleapis/google-http-java-client/pull/572))
- depend directly on Apache httpclient ([#591](https://github.com/googleapis/google-http-java-client/pull/591))
- upgrade dependencies ([#596](https://github.com/googleapis/google-http-java-client/pull/596))
- more fixes for Java 7 minimum …
=> Release google-http-java-client v1.29.0

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-legacy/pom.xml, google-http-client-apache/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
Reverts googleapis/google-http-java-client#605 - to be released at a later time.
=> Revert "Release google-http-java-client v1.29.0"

google-http-client-test/src/main/java/com/google/api/client/test/json/AbstractJsonFactoryTest.java, google-http-client/src/main/java/com/google/api/client/json/JsonParser.java
Using with Jackson2 parser,  a simple parsing of { "data" : 1} gives a BigDecimal instead an integer. In my case, ``valueClass`` is Object, but the JSON current token is VALUE_NUMBER_INT not FLOAT.
I parse as a Map. No problem if I parse as a class with "int" type.
=> Fix int type transformed as BigDecimal value when parsing as Map

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-legacy/pom.xml, google-http-client-apache/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
04-25-2019 11:31 PDT
- Fix int type transformed as BigDecimal value when parsing as Map ([#529](https://github.com/googleapis/google-http-java-client/pull/529))
- Remove jdo artifact from BOM ([#624](https://github.com/googleapis/google-http-java-client/pull/624))
- Remove assembly artifact from BOM ([#627](https://github.com/googleapis/google-http-java-client/pull/627))
- Update opencensus to 0.19.2, remove jdo dependency ([#628](https://github.com/googleapis/google-http-java-client/pull/628))
- Add publish javadoc kokoro job ([#631](https://github.com/googleapis/google-http-java-client/pull/631))
- .classpath no longer seems to exist ([#625](https://github.com/googleapis/google-http-java-client/pull/625))
=> Release google-http-java-client v1.29.1

.gitignore, 404.html, package.json, src/redirects.js, test/redirects.js
Add a custom 404 page to `gh-pages` which will handle redirects to the new javadocs site.
When the javadocs are published, we can remove the `releases` folder and this 404 page should redirect to the correct page. The node code is used to manually test the `redirectPath` functionality but is not run by a CI suite (doesn't apply to master).
Rather than sharing the same script (and trying to load modules across npm and the browser) the `redirectPath` function is copied from `src/redirects.js` inline in the `404.html`.
=> Add 404 redirect to new javadoc site

google-http-client/src/main/java/com/google/api/client/util/Data.java
When loading generated data classes concurrently the ProGuard protection which calls Data.nullOf in a static initializer can result in a deadlock on the Data.NULL_CACHE lock. The fix is to emulate ConcurrentMap.computeIfAbsent to protect against blocking during concurrent populate of the cache.
Fixes #638
=> Fix deadlock caused by concurrent class loading

google-http-client/src/main/java/com/google/api/client/util/ClassInfo.java
Replaces blocking logic in ClassInfo.of with ConcurrentMap.computeIfAbsent.
Also removes WeakHashMap as it wasn't actually doing the intended operation. The ClassInfo value has a strong reference to the Class which prevents the weak key reference from ever being collected.
Fixes #642
=> Remove blocking ClassInfo.of

google-http-client/src/main/java/com/google/api/client/util/Base64.java, google-http-client/src/test/java/com/google/api/client/util/Base64Test.java
When we switched from Apache commons-codec to Guava's base64 decoder, we missed a behavioral edge case. Apache's implementation could handle trailing whitespace while Guava's cannot.
=> Add Base64Test case for some base64 decoding edge cases

google-http-client-test/src/main/java/com/google/api/client/test/json/AbstractJsonFactoryTest.java, google-http-client/src/main/java/com/google/api/client/json/JsonParser.java
reverts "Fix int type transformed as BigDecimal value when parsing as …Map (#529)"
This reverts commit da597e87b9d7463de4eb7da55256c648d28fe3ba.
See #664 
This commit breaks many internal customers. It also now crashing when you pass it a very large integer. We can possibly try to parse as and Integer and if it overflows, then parse as a BigInteger or BigDecimal, but then as a consumer, you are unsure of what type of value you will see. We should revert this behavior and then add a unit test separately to prevent regression.
=> Revert #529

google-http-client-gson/src/test/java/com/google/api/client/json/gson/GsonParserTest.java, google-http-client-jackson2/src/test/java/com/google/api/client/json/jackson2/JacksonParserTest.java, google-http-client-test/src/main/java/com/google/api/client/test/json/AbstractJsonParserTest.java
See #664 
This should fail until we revert #529
=> Add abstract JSON test and tests for Jackson2 and gson

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-legacy/pom.xml, google-http-client-apache/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
06-03-2019 10:13 PDT
- Revert "Fix int type transformed as BigDecimal value when parsing as Map ([#529](https://github.com/googleapis/google-http-java-client/pull/529))" ([#662](https://github.com/googleapis/google-http-java-client/pull/662))
- Add abstract JSON test and tests for Jackson2 and gson ([#665](https://github.com/googleapis/google-http-java-client/pull/665))
- Bump next snapshot ([#634](https://github.com/googleapis/google-http-java-client/pull/634))
=> Release google-http-java-client v1.29.2

pom.xml
We want to keep the opencensus version at the same place grpc is currently at.
=> Update dependency io.opencensus:opencensus-api to v0.21.0

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-v2/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
06-03-2019 16:12 PDT
- Revert "Fix int type transformed as BigDecimal value when parsing as Map ([#529](https://github.com/googleapis/google-http-java-client/pull/529))" ([#662](https://github.com/googleapis/google-http-java-client/pull/662))
- Remove deprecated google-http-client-jackson artifact. ([#647](https://github.com/googleapis/google-http-java-client/pull/647))
- Remove blocking ClassInfo.of ([#643](https://github.com/googleapis/google-http-java-client/pull/643))
- Fix deadlock caused by concurrent class loading ([#639](https://github.com/googleapis/google-http-java-client/pull/639))
- Republish the fixed apache extensions as google-http-client-apache-v2 ([#637](https://github.com/googleapis/google-http-java-client/pull/637))
- …
=> Release google-http-java-client v1.30.0

google-http-client/src/main/java/com/google/api/client/util/Data.java, google-http-client/src/test/java/com/google/api/client/util/DataTest.java
=> Fix Data.nullOf method template signature regression

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-v2/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
06-06-2019 10:13 PDT
- Fix method template signature broken in [#639](https://github.com/google/google-http-java-client/pull/639) ([#700](https://github.com/google/google-http-java-client/pull/700))
- Bump next snapshot ([#698](https://github.com/google/google-http-java-client/pull/698))
=> Release google-http-java-client v1.30.1

.kokoro/release/stage.cfg, .kokoro/release/stage.sh, pom.xml
=> Enable autorelease

google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpTransport.java
=> Expose the default HttpClientBuilder so users can customize further

.kokoro/build.bat, .kokoro/continuous/java8-win.cfg, .kokoro/presubmit/java8-win.cfg, google-http-client/src/test/java/com/google/api/client/util/IOUtilsTest.java, pom.xml
* skip maven-checkstyle-plugin as our exclusion list uses unix-style paths
* relax the required maven version to 3.5.2 as that's what our test runner currently has installed
* use NIO to symlink the file in the IOUtilsTest rather than shelling out to run `ln`
=> Configure Kokoro CI for Windows

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/http/OpenCensusUtils.java, google-http-client/src/main/java/com/google/api/client/json/JsonParser.java
=> Clean up javadoc warnings in OpenCensusUtils

google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpRequest.java, google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpTransport.java
Fixes #715
Switch back to deprecated `setStaleConnectionCheck`. `HttpClientBuilder` does not expose a way to configure the connection manager's `validateAfterInactivity` configuration. We can either reimplement the entirety of the builder's logic or switch back to a deprecated method.
=> Fix ApacheHttpTransport configuration

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-v2/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
06-21-2019 12:37 PDT
- Fix ApacheHttpTransport configuration ([#717](https://github.com/googleapis/google-http-java-client/pull/717))
=> Release google-http-java-client v1.30.2

.kokoro/release/publish_javadoc.sh
This will add links to the version selector overlay with links to this repo and to file issues.
=> Add GitHub repo, issue tracker metadata for javadoc site

google-http-client/src/main/java/com/google/api/client/util/DateTime.java, google-http-client/src/test/java/com/google/api/client/util/DateTimeTest.java
The original parseRfc3339 method of `DateTime` returns a `DateTime` instance that has millisecond precision. The parse method therefore also disregards any time information beyond millisecond precision. For Spanner we would like to add nanosecond precision, and instead of replicating the parse method in the Spanner specific libraries, this change will add nanosecond support to this parse method, while retaining the original behavior of the parseRfc3339 method.
The original parseRfc3339 method allows strings to contain more than millisecond precision. It does however not specify exactly what it does with any additional information, and the behavior is not consistent:
* The input value `2018-12-31T23:59:59.9999Z` would be truncated to `2018-12-31T23:59:59.999Z`
* The input value …
=> Add support for nanosecond precision when parsing rfc3339 strings

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-v2/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
07-31-2019 07:21 PDT
- Fix ApacheHttpTransport configuration ([#717](https://github.com/googleapis/google-http-java-client/pull/717))
- Add support for nanosecond precision when parsing rfc3339 strings ([#752](https://github.com/googleapis/google-http-java-client/pull/752))
- Use NIO to set file permissions ([#557](https://github.com/googleapis/google-http-java-client/pull/557))
- Expose the default HttpClientBuilder so users can customize further ([#713](https://github.com/googleapis/google-http-java-client/pull/713))
- Update dependency org.apache.maven.plugins:maven-site-plugin to v3.8.2 ([#753](https://github.com/googleapis/google-http-java-client/pull/753))
- Update dependency mysql:mysql-connector-java to v8.0.17 …
=> Release google-http-java-client v1.31.0

google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpTransport.java, google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/package-info.java, google-http-client-test/src/main/java/com/google/api/client/test/json/AbstractJsonGeneratorTest.java, google-http-client-test/src/main/java/com/google/api/client/test/json/AbstractJsonParserTest.java, google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpTransport.java, google-http-client/src/main/java/com/google/api/client/util/FieldInfo.java, google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java, google-http-client/src/test/java/com/google/api/client/util/GenericDataTest.java
=> remove deprecated code, fix warnings, and use JUnit 4

google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebSignature.java, google-http-client/src/test/java/com/google/api/client/json/webtoken/JsonWebSignatureTest.java
Also converts test to JUnit 4
@salrashid123
=> stop exposing internal private state

versions.txt
Last release was 1.28.0. Then it was deleted.
=> Remove google-http-client-jdo

pom.xml
This is not bound to any executions so I don't think we're using it.
=> remove maven jarjar plugin

clirr-ignored-differences.xml, google-http-client/src/main/java/com/google/api/client/testing/http/MockHttpTransport.java
Fixes #772 @chingor13 
Noticed this one because of a warning in the build
=> Remove deprecated testing method

pom.xml
Per https://github.com/sonatype/oss-parents
"This project is no longer active or supported. We suggest to manage parent POM files for your own organization as needed. The POM files from this project no longer work with latest Maven and/or Java versions."
=> remove obsolete and deprecated parent

README.md
Note: content from https://developers.google.com/api-client-library/java/google-http-java-client/ was copied to this repo's wiki pages. Redirects will be set up to point to this repository after we fix this README.
=> Point README developer guide and setup instructions to the GitHub wiki

google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpRequest.java, google-http-client-apache-v2/src/test/java/com/google/api/client/http/apache/v2/ApacheHttpTransportTest.java
=> fix: disable uri normalization in ApacheHttpRequest

google-http-client-apache-v2/src/main/java/com/google/api/client/http/apache/v2/ApacheHttpRequest.java, google-http-client-apache-v2/src/test/java/com/google/api/client/http/apache/v2/ApacheHttpTransportTest.java
=> fix: correct connect timeout setting for ApacheHttpRequest

google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/resources/google-http-client.properties, google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java, pom.xml
Fixes #796
This PR allows the HttpClient to inspect its own version at start time. If it's running from a package, it can fetch the version from the package manifest's implementation version. If it's not, it can read it from a properties file created at compile time to read the version.
Note that this is similar to how gax inspects its own version for the x-goog-api-client header
=> fix: grab version from the package metadata

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-apache-v2/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-bom/README.md, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, versions.txt
09-11-2019 10:34 PDT
- fix: grab version from the package metadata ([#806](https://github.com/google/google-http-java-client/pull/806))
- fix: correct connect timeout setting for ApacheHttpRequest ([#803](https://github.com/google/google-http-java-client/pull/803))
- fix: disable uri normalization in ApacheHttpRequest ([#804](https://github.com/google/google-http-java-client/pull/804))
- fix: OpenCensus spans should close on IOExceptions ([#797](https://github.com/google/google-http-java-client/pull/797))
- remove deprecated methods ([#769](https://github.com/google/google-http-java-client/pull/769))
- stop exposing internal private state in JsonWebSignature ([#767](https://github.com/google/google-http-java-client/pull/767))
- …
=> Release google-http-java-client v1.32.0

docs/http-transport.md
=> fixed HttpResponseException Markup (#1)

google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/http/OpenCensusUtils.java, google-http-client/src/test/java/com/google/api/client/http/HttpRequestTracingTest.java, google-http-client/src/test/java/com/google/api/client/http/OpenCensusUtilsTest.java, pom.xml
=> revert: "feat: remove opencensus (#834)"

google-http-client/src/main/java/com/google/api/client/http/ConsumingInputStream.java, google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/ConsumingInputStreamTest.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
If a connection is closed and there are some bytes that have not
been read that connection can't be reused. Now GZIPInputStream
will have all of its bytes read on close automatically to promote
connection reuse.
Cherry-picked: #749
Fixes: #367
=> feat: wrap GZIPInputStream for connection reuse

docs/_layouts/default.html
Where the page is hosted is not something readers want to know. @chingor13
=> Remove theme details

google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
Fixes #842 by having HttpResponse compare (case insensitive) the content-encoding against "gzip" and "x-gzip" (HTTP 1.1).
=> fix: HttpResponse GZip content encoding equality change

google-http-client/src/main/java/com/google/api/client/http/HttpStatusCodes.java, google-http-client/src/test/java/com/google/api/client/http/HttpStatusCodesTest.java
=> fix: redirect on 308 (Permanent Redirect) too

google-http-client/src/main/java/com/google/api/client/http/GenericUrl.java, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/http/UriTemplate.java, google-http-client/src/main/java/com/google/api/client/http/UrlEncodedParser.java, google-http-client/src/test/java/com/google/api/client/http/GenericUrlTest.java
Fixes #864 
At the moment I have no actual way to test it, as I failed to use `1.33.1-SNAPSHOT` with Jib (any helping hand is more than welcome).
=> feat: add option to pass redirect Location: header value as-is without encoding, decoding, or escaping

google-http-client/src/main/java/com/google/api/client/util/DateTime.java, google-http-client/src/test/java/com/google/api/client/util/DateTimeTest.java
Fixes #894 @suztomo @olavloite @codyoss
=> fix millisecond parsing errors

google-http-client/src/test/java/com/google/api/client/util/DateTimeTest.java
Follow up of https://github.com/googleapis/google-http-java-client/pull/895#discussion_r350369850 .
It's because the calendar system has changed from Julian to Gregorian on that day. The 10 days before that day have been skipped to adjust the difference between Gregorian calendar and Julian calendar.
> the calendar's adoption, Friday, 15 October 1582, the preceding date was Thursday, 4 October 1582 (Julian calendar).
https://en.wikipedia.org/wiki/Gregorian_calendar
=> Adding test for Gregorian Calendar beginning day

docs/setup.md
Libraries-bom 3.1.0 has been released. https://search.maven.org/artifact/com.google.cloud/libraries-bom/3.1.0/pom
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for context and/or discussion)
=> Libraries-bom 3.1.0 release

google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
Fixes issue #905 by setting mediaType to null if the contentType is invalid.
=> fix: set mediaType to null if contentType cannot be parsed

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java
The original implementation of `getVersion` used the implementation
version of the package of the declaring class, however there is
differing behavior between Android and openjdk based jvms.
In order to be consistent across platforms we will now always resolve
the value from the `google-http-client.properties` file that is
generated during the build. This method should be stable as it based
on loading a classpath resource which has cross jvm support.
Fixes #892
=> fix: update HttpRequest#getVersion to use stable logic

google-http-client/src/main/java/com/google/api/client/http/GenericUrl.java, google-http-client/src/main/java/com/google/api/client/util/escape/CharEscapers.java, google-http-client/src/main/java/com/google/api/client/util/escape/PercentEscaper.java, google-http-client/src/test/java/com/google/api/client/http/GenericUrlTest.java, google-http-client/src/test/java/com/google/api/client/util/escape/CharEscapersTest.java
The old implementation was incorrectly treating '+' as a space. Now
the only things that get decoded in the path are uri escaped sequences.
Fixes #398
=> feat: decode uri path components correctly

docs/setup.md
@BenWhitehead @chingor13 @elharo Would you approve/merge this?
=> docs: libraries-bom 3.3.0

google-http-client/src/main/java/com/google/api/client/http/MultipartContent.java, google-http-client/src/test/java/com/google/api/client/http/MultipartContentTest.java
Fixes #909 
Fixes https://github.com/googleapis/google-cloud-java/issues/6386
=> fix: use random UUID for multipart boundary delimiter

google-http-client/src/main/java/com/google/api/client/http/AbstractInputStreamContent.java, google-http-client/src/main/java/com/google/api/client/http/ExponentialBackOffPolicy.java, google-http-client/src/main/java/com/google/api/client/json/JsonParser.java, google-http-client/src/main/java/com/google/api/client/json/JsonString.java, google-http-client/src/main/java/com/google/api/client/testing/json/webtoken/TestCertificates.java, google-http-client/src/main/java/com/google/api/client/util/PemReader.java
Fixes the following warnings:
> [WARN] /home/anusien/opensource/google-http-java-client/google-http-client/src/main/java/com/google/api/client/testing/json/webtoken/TestCertificates.java:242: Empty line should be followed by <p> tag on the next line. [JavadocParagraph]
> [WARN] /home/anusien/opensource/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/AbstractInputStreamContent.java:32: <p> tag should be placed immediately before the first word, with no space after. [JavadocParagraph]
> [WARN] /home/anusien/opensource/google-http-java-client/google-http-client/src/main/java/com/google/api/client/http/ExponentialBackOffPolicy.java:33: Empty line should be followed by <p> tag on the next line. [JavadocParagraph]
> [WARN] …
=> Fix various paragraph issues in javadoc

google-http-client/src/main/java/com/google/api/client/util/escape/PercentEscaper.java
=> fix: SAFEPATHCHARS_URLENCODER includes +

google-http-client/src/main/java/com/google/api/client/util/escape/CharEscapers.java, google-http-client/src/test/java/com/google/api/client/util/escape/PercentEscaperTest.java
@frankyn I can't find any evidence that my previous change had an effect here.
=> add PercentEscaperTest

google-http-client/src/main/java/com/google/api/client/util/escape/PercentEscaper.java, google-http-client/src/test/java/com/google/api/client/util/escape/PercentEscaperTest.java
@chingor13 @frankyn This should be fully backwards compatible at an an API and behavior level. However it does strongly warn developers not to encode spaces as plus. I'd prefer to disable that completely, but the last time we tried that it broke some downstream projects, so this is a more nudging approach to get clients to stop doing this.
=> Deprecate plusForSpace

google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/JacksonFactory.java, google-http-client-xml/src/main/java/com/google/api/client/xml/atom/Atom.java, google-http-client/src/main/java/com/google/api/client/http/GenericUrl.java, google-http-client/src/main/java/com/google/api/client/http/UrlEncodedParser.java, google-http-client/src/main/java/com/google/api/client/util/escape/CharEscapers.java, google-http-client/src/test/java/com/google/api/client/http/ConsumingInputStreamTest.java, google-http-client/src/test/java/com/google/api/client/util/escape/CharEscapersTest.java
=> More work toward removing plusForSpace

google-http-client/src/main/java/com/google/api/client/http/UriTemplate.java, google-http-client/src/main/java/com/google/api/client/util/escape/CharEscapers.java, google-http-client/src/test/java/com/google/api/client/http/UriTemplateTest.java
=> fix: use %20 to escape spaces in URI templates

google-http-client-android/pom.xml
@kolea2 This has the effect of upgrading commons-logging to 1.2 from 1.1.1
=> deps: move more up to date dependencies first

google-http-client/src/main/java/com/google/api/client/json/JsonParser.java
changed switch parameter in parseValue from calling getCurrentToken() again to just declared and assigned local member "token" two lines above
Fixes #982
=> fix for #982

google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
Fixes #367 (see my last comment on that issue)
The fix done in #840 is incorrect if not inadequate. It doesn't properly cleanup the last chunk of a chunked response when the response is also gzipped. This in turns prevents proper connection reuse. 
This PR addresses this issue.
=> fix: Correctly handling chunked response streams with gzip

google-http-client/src/main/java/com/google/api/client/http/HttpResponseException.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseExceptionTest.java
This will allow to simplify debugging of failed requests, especially requests that are issued by [`MediaHttpUploader`](https://github.com/googleapis/google-api-java-client/blob/master/google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java) (not created directly by library clients).
For example, it's useful to have an access to `upload_id` for failed resumable upload requests.
=> fix: include request method and URL into HttpResponseException message

README.md
@chingor13 @BenWhitehead We now require API 19 or higher which means Android 4.4 or later.
=> docs: require Android 4.4

google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java
The "Windows" part of `os.name` is not always uppercase. On Windows 10 for example I get `"Windows 10"`, which does not pass the current check. This leads to `setPermissionsToOwnerOnly` instead of `setPermissionsToOwnerOnlyWindows` being executed, which then issues the following warning (and does nothing): `Unable to set permissions for C:\example, because you are running on a non-POSIX file system`
Fixes #953
=> fix: incorrect check for Windows OS in FileDataStoreFactory

google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java
=> handle all exceptions equally

google-http-client-android/AndroidManifest.xml
@chingor13 hard to believe this was set to Android 1.6, Donut.
fixes #1015
=> set minimum API level to 19 a.k.a. 4.4 Kit Kat

docs/setup.md
=> docs: libraries-bom 5.2.0

google-http-client/src/main/java/com/google/api/client/json/webtoken/DerEncoder.java, google-http-client/src/main/java/com/google/api/client/json/webtoken/JsonWebSignature.java, google-http-client/src/main/java/com/google/api/client/util/SecurityUtils.java, google-http-client/src/test/java/com/google/api/client/json/webtoken/JsonWebSignatureTest.java
Adds logic for verifying signatures that use NIST P-256 (ES256). It is up to the caller to provide the correct public key for verification.
Note that the difference between the ES256 and RS256 verification process is that ES256 requires AS1 (DER) notation for the signature so we do a limited conversion here before providing the signature to the signing algorithm.
Logic will be added to `google-auth-library` for handling Google's well-known, published public keys.
=> feat: add logic for verifying ES256 JsonWebSignatures

docs/setup.md
Libraries BOM 7.0.0 https://search.maven.org/artifact/com.google.cloud/libraries-bom/7.0.0/pom
(It's 7.0.0 because I messed up the 6.0.0 version.)
@chingor13 @elharo  Would you review and merge this?
=> chore(docs): libraries-bom 7.0.0

.github/CODEOWNERS, .github/workflows/ci.yaml, .kokoro/build.sh, .kokoro/dependencies.sh, .kokoro/nightly/integration.cfg, .kokoro/nightly/samples.cfg, .kokoro/populate-secrets.sh, .kokoro/presubmit/integration.cfg, .kokoro/presubmit/samples.cfg, .kokoro/trampoline.sh, .repo-metadata.json, CONTRIBUTING.md, synth.metadata, synth.py
=> chore: regenerate common templates

google-http-client-android/src/main/java/com/google/api/client/extensions/android/util/store/FileDataStoreFactory.java, google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java, pom.xml
Fixes #906
* Adds an Android compatible FileDataStoreFactory implementation (version prior to switching to NIO) in the google-http-client-android extensions artifact
* Adds a note in the core FileDataStoreFactory to use the new version on Android API level < 26
* Adds an animal-sniffer check for Android API level 19 (Ignores the NIO Files API usage).
=> feat: add Android 19 compatible FileDataStoreFactory implementation

docs/setup.md
Libraries BOM 9.0.0 is available now In Maven Central: https://search.maven.org/artifact/com.google.cloud/libraries-bom/9.0.0/pom
=> deps: libraries-bom 9.0.0

docs/setup.md
=> docs: libraries-bom 12.0.0

pom.xml
@BenWhitehead This is unsupported and we don't use it anyway
=> chore(deps): remove commons logging version

google-http-client-gson/src/main/java/com/google/api/client/json/gson/GsonFactory.java
@BenWhitehead referenced issue was rightly closed
=> fix: JSON spec mandates UTF-8

google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/JacksonFactory.java, google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/JacksonGenerator.java, google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/JacksonParser.java
fixes #1214 
@BenWhitehead as discussed in the Tuesday meeting
=> fix: deprecate JacksonFactory to align with security team advice

google-http-client-xml/src/main/java/com/google/api/client/xml/Xml.java, google-http-client/src/main/java/com/google/api/client/util/Data.java, google-http-client/src/test/java/com/google/api/client/util/ObjectsTest.java
=> fix: fix some deprecation warnings in Java 9+

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/test/java/com/google/api/client/http/HttpRequestTracingTest.java
This one is fairly straight forward:
It adds the official OpenTelemetry http.status_code attribute which is [mandatory](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-http.md
), was missing and is very useful to know what happened to one's request.
Signed-off-by: CI-Bot for Emmanuel Courreges <emmanuel.courreges@orange.com>
=> add http.status_code attribute to all Spans that have a lowLevelHttpResponse 

google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java
=> unused logger

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/util/Base64.java, google-http-client/src/main/java/com/google/api/client/util/Beta.java, google-http-client/src/main/java/com/google/api/client/util/ByteArrayStreamingContent.java, google-http-client/src/main/java/com/google/api/client/util/ByteStreams.java, google-http-client/src/main/java/com/google/api/client/util/Charsets.java, google-http-client/src/main/java/com/google/api/client/util/Collections2.java, google-http-client/src/main/java/com/google/api/client/util/IOUtils.java, google-http-client/src/main/java/com/google/api/client/util/StreamingContent.java, google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java
=> chore: deprecate obsolete utility methods

pom.xml
=> deps: update OpenCensus for consistency with gRPC

pom.xml
Fixes the dependencies presubmits
=> deps: version manage error_prone_annotations to 2.5.1

google-http-client-jackson2/src/main/java/com/google/api/client/json/jackson2/package-info.java
Perhaps this is the one causing us trouble in the Java 11 CI check. In any case the link I remove here is 404.
Fixes #1278
=> fix: remove old broken link

.github/sync-repo-settings.yaml
The GitHub Actions have been enabled in this repository. I believe we no longer need the Kokoro builds here.
---
=> ci: removing Kokoro settings that are covered by GitHub Actions

google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
=> fix: default application/json charset to utf-8

google-http-client-apache-v2/src/test/java/com/google/api/client/http/apache/v2/ApacheHttpTransportTest.java, google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpTransportTest.java
Adds a test to the `NetHttpTransport` and `ApacheHttpTransport` to make sure we don't wait until all the content is read when disconnecting the response.
Fixes #1303
=> fix: when disconnecting, close the underlying connection before the response InputStream

docs/setup.md
=> docs: libraries-bom 20.1.0

google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
=> Fix: Use BufferedInputStream to inspect HttpResponse error

google-http-client/pom.xml
This PR changes the configuration of the `maven-bundle-plugin` so that the generated `MANIFEST.MF` declares the runtime depencency on `javax.annotation` as optional.
This way, OSGI environments try not to resolve `javax.annotation` from findbugs that could collide with `javax.annotation` from other bundles.
> No source Code was changed
> Not necessary
Fixes #1323  ☕️
=> fix: make dependency on javax.annotation optional (#1323)

google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
Some servers don't return the charset. This causes german
characters to be encoded incorrectly, since ISO_8859_1 does not
work very well in such cases defaulting to UTF-8 if its missing.
https://www.iana.org/assignments/media-types/text/csv
Fixes #1421  ☕️
=> fix: default charset to UTF-8 for text/csv if not specified

pom.xml
There is a [vulnerability](https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327) in the gson library <=2.2.8, which has been fixed in 2.8.9
=> deps: update dependency com.google.code.gson:gson to v2.8.9

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/http/HttpResponseException.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseExceptionTest.java
This adds number of requests attempted to httpRequestException. This makes sense to know how many attempts were made since HttpRequest supports automated retries. We want to use it to improve user experience of Auth library, that leverages HttpRequest retry functionality. 
For more details on the feature: go/auth-correct-retry
=> feat: add AttemptCount to HttpResponseException

docs/setup.md
Libraries BOM 24.3.0 release documentation update in google-http-java-client repository.
=> chore(docs): libraries-bom 24.3.0 in google-http-java-client

.github/.OwlBot.lock.yaml, .github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/approve-readme.yaml, .github/workflows/auto-release.yaml, .github/workflows/ci.yaml, .github/workflows/downstream.yaml, .kokoro/build.bat, .kokoro/downstream-client-library-check.sh, .kokoro/nightly/java11-integration.cfg, README.md
Test core java libraries in java client libraries before release. Feature/code changes introduced in each PR can be tested on downstream java client libraries by adding `downstream-check:run` label. For now, unit tests are being run.
Next phase involves running samples and integration tests.
Note: Some of these tests are expected to fail due to individual client library conditions and do block the merging of this PR.
=> chore: downstream check for all libraries in single job

.github/sync-repo-settings.yaml
@Neenu1995 The check came back as "Required". I think we need to edit this file.
=> ci: not requiring lint until Owlbot migration finishes

google-http-client/src/main/java/com/google/api/client/http/GzipSupport.java, google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/GzipSupportTest.java, google-http-client/src/test/java/com/google/api/client/http/HttpRequestTracingTest.java
When `GZIPInputStream` completes processing an individual member it will call `InputStream#available()`
to determine if there is more stream to try and process. If the call to `available()` returns 0
`GZIPInputStream` will determine it has processed the entirety of the underlying stream. This is
spurious, as `InputStream#available()` is allowed to return 0 if it would require blocking in order
for more bytes to be available. When `GZIPInputStream` is reading from a `Transfer-Encoding: chunked`
response, if the chunk boundary happens to align closely enough to the member boundary
`GZIPInputStream` won't consume the whole response.
Add new `OptimisticAvailabilityInputStream`, which provides an optimistic "estimate" of the number of
`available()` bytes in the underlying stream. When …
=> fix: `Content-Encoding: gzip` along with `Transfer-Encoding: chunked` sometimes terminates early

google-http-client/pom.xml, google-http-client/src/main/java/com/google/api/client/util/SslUtils.java
In the monorepo, this blocks the build from succeeding.
Fixes #1710.
=> fix: add `@CanIgnoreReturnValue` to avoid errorprone errors.

.github/.OwlBot.lock.yaml, renovate.json
Reverts googleapis/google-http-java-client#1726
=> Revert "chore: pin versions of dependencies for compatibility with Python 3.6 (#1588)"

google-http-client-gson/src/main/java/com/google/api/client/json/gson/GsonFactory.java, google-http-client-gson/src/main/java/com/google/api/client/json/gson/GsonParser.java, google-http-client-gson/src/test/java/com/google/api/client/json/gson/GsonFactoryTest.java, google-http-client-gson/src/test/java/com/google/api/client/json/gson/GsonParserTest.java
Fixes b/269515918, where the prefix `)]}'\n` for Cross-site script inclusion (XSSI) didn't work for GsonFactory.
Users will call `GsonFactory.getDefaultInstance().withReadLeniency()` when they want this library to process JSON input that may have the prefix.
- For this pull request, it controlls only the leniency when reading input JSON. This design `withReadLeniency()` gives flexibility for us to choose writeLeniency in future if necessary. (It's possible that read leniency is true and write leniency is false.)
- Because this creates a copy of the instance, it does not affect existing usage of GsonFactory. (No global state in GsonFactory)
=> feat: GsonFactory to have read leniency option

pom.xml
This matches OwlBot Java post procesosr
https://github.com/googleapis/synthtool/blob/5f2a6089f73abf06238fe4310f6a14d6f6d1eed3/docker/owlbot/java/Dockerfile#L22
Downgrading fmt-maven-plugin to 2.9 because the new one does not run with Java 8.
=> ci: fmt-maven-plugin 2.9 with google-java-format 1.7

google-http-client/src/main/java/com/google/api/client/util/FieldInfo.java, google-http-client/src/test/java/com/google/api/client/util/FieldInfoTest.java
Fixes the problem of JSON deserialization ignoring the case of setters. Now case-sensitive setter method matches are considered first.
Fixes: #1830.
=> fix: JSON deserialization setter case priority

google-http-client/pom.xml
List of classes that use commons-logging in `org:apache:httpcomponents:httpclient`:
List of classes that use `org:apache:httpcomponents:httpclient` in google-http-java-client:
Fortunately there's no overlap. Indeed the tests pass.
=> deps: testing exlcusing commons-logging

google-http-client/pom.xml, pom.xml
Part of https://github.com/googleapis/google-api-java-client/issues/2416
=> deps: newer grpc-context to override old one

google-http-client-android/pom.xml, google-http-client-apache-v2/pom.xml, google-http-client-appengine/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml
The release job is currently failing with:
```
[INFO] Parent for the Google HTTP Client Library for Java . SUCCESS [  6.038 s]
[INFO] Google HTTP Client Library for Java ................ FAILURE [  8.781 s]
[INFO] Android Platform Extensions to the Google HTTP Client Library for Java. SKIPPED
[INFO] Apache HTTP transport v2 for the Google HTTP Client Library for Java. SKIPPED
[INFO] Shared classes used for testing of artifacts in the Google HTTP Client Library for Java. SKIPPED
[INFO] Google App Engine extensions to the Google HTTP Client Library for Java. SKIPPED
[INFO] GSON extensions to the Google HTTP Client Library for Java. SKIPPED
[INFO] Jackson 2 extensions to the Google HTTP Client Library for Java. SKIPPED
[INFO] Protocol Buffer extensions to the Google HTTP Client Library for …
```
=> chore: fix declaration of maven-source-plugin for v3.3.0

google-http-client/src/main/java/com/google/api/client/util/Base64.java, google-http-client/src/test/java/com/google/api/client/util/Base64Test.java
Using b/274482271#comment3 by @eamonnmcmanus
- Added test cases for new line characters.
- This PR keeps the `trim()` method that was also added for the compatibility.
=> fix: Base64 decoding to discard newline characters

renovate.json
Dependency Dashboard is not updating PRs. Using renovate's suggested migration config to see if that will fix it.
=> chore: Use renovate's suggested config

renovate.json
For #1964 
This PR:
- Corrects the config to update `native-image-shared-config` in the POM.
- Emulate config settings in sdk-platform-java's [renovate.json](https://github.com/googleapis/sdk-platform-java/blob/main/renovate.json)
=> chore: fix renovate bot settings for native-image-shared-config pom update

renovate.json
Guava v31+ seems to support Java 8+. Try to limit to Guava v30 and see if this resolves the renovate issue.
=> chore: Limit guava version to v30

pom.xml
As discovered in https://github.com/googleapis/google-http-java-client/pull/1975,  running `mvn clean install` in jdk 21 is results in the following error:
```
INFO] Compiling 157 source files with javac [debug target 1.7] to target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] bootstrap class path not set in conjunction with -source 7
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 7 is no longer supported. Use 8 or later. …
```
=> chore: add java 21 profile

.kokoro/presubmit/common.cfg, .kokoro/presubmit/graalvm-native-a.cfg, .kokoro/presubmit/graalvm-native-b.cfg, renovate.json
Notable Changes:
- Removed unused keystore settings.
- Replaced use of TRAMPOLINE_IMAGE environment variable with `container_properties { docker_image ...}}`
- Modified renovate bot settings to edit new docker_image property's value when a new version of java-shared-config is available.
=> chore: migrate graalvm jobs to kokoro instance pool

.github/workflows/ci.yaml, google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpTransportTest.java
Fixes https://github.com/googleapis/google-http-java-client/issues/2063
Thanks to @ldetmer and @burkedavison for the pointers on how to solve this.
The approach is to `flush()` a first byte in the test pointed out by the issue. That triggers sending the headers and unblocks `NetHttpResponse.<init>`
=> feat: support JDK 23

google-http-client-appengine/pom.xml, google-http-client-bom/pom.xml, google-http-client-findbugs/pom.xml, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, samples/pom.xml
b/356854847
- Avoid declaring nexus staging plugin. It's already configured in native-image-shared-config.
- Move check-related plugin activations to profiles.
=> fix: remove unnecessary nexus plugin activation

google-http-client/src/main/java/com/google/api/client/util/escape/PercentEscaper.java, google-http-client/src/test/java/com/google/api/client/http/UrlEncodedContentTest.java
Currently we are not encoding + signs if it part of the URL path, while this [is to spec](https://www.rfc-editor.org/rfc/rfc1738.html)
Thus, only alphanumerics, the special characters "$-_.+!*'(),", and
reserved characters used for their reserved purposes may be used
unencoded within a URL.
It MAY be encoded.
Originally we did encode plus signs, but inappropriately as a space (%20).  This was fixed in this [PR](https://github.com/googleapis/google-http-java-client/pull/913) .  However the fix did 2 things, it stopped treating the + sign as a space, but it also stopped encoding it at all.  Technically it only need the first fix [here](https://github.com/googleapis/google-http-java-client/blob/main/google-http-client/src/main/java/com/google/api/client/http/GenericUrl.java#L591).  Removing …
=> fix: encode plus sign in url with %2B

.github/workflows/ci.yaml
this is order to support latest graalvm update
=> chore: update ci tests to run against jdk 24
