google-http-client/src/main/java/com/google/api/client/util/Data.java, google-http-client/src/test/java/com/google/api/client/util/DataTest.java
Resolves #293
@davidadamsphd, are you able to give this a try?
=> Support Arrays.asList in GenericData cloning

google-http-client/src/test/java/com/google/api/client/http/javanet/NetHttpTransportTest.java
-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=107271660
=> Convert unnecessary large test to small.

samples/dailymotion-simple-cmdline-sample/pom.xml, samples/googleplus-simple-cmdline-sample/pom.xml
This should fix the Travis-CI build.
=> Fix missed version bump for samples

google-http-client/src/main/java/com/google/api/client/http/HttpStatusCodes.java
-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=166307565
=> Adds STATUS_CODE_UNPROCESSABLE_ENTITY 422 http error to HttpStatusCodes

google-http-client/src/main/java/com/google/api/client/util/Base64.java, google-http-client/src/test/java/com/google/api/client/util/Base64Test.java
=> Replace Base64 from Apache Commons Codec with equivalent from Guava.

pom.xml
=> Update dependency FindBugs to 3.0.2

.travis.yml, google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java, google-http-client/src/main/java/com/google/api/client/testing/http/apache/MockHttpClient.java, google-http-client/src/test/java/com/google/api/client/http/apache/ApacheHttpTransportTest.java, pom.xml
=> Bump version of Apache httpclient.

google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpTransport.java
Hi @mattwhisenhunt : quick followup from Wouter's [comment](https://github.com/google/google-http-java-client/pull/361#pullrequestreview-79987978) on https://github.com/google/google-http-java-client/pull/361
Also refactoring the property into a constant, to ensure it is consistently used.
=> fixing should use proxy flag

google-http-client/src/main/java/com/google/api/client/http/UrlEncodedParser.java, google-http-client/src/test/java/com/google/api/client/http/UrlEncodedParserTest.java
allow '=' in query parameter value
=> allow '=' in query parameter value

google-http-client/src/main/java/com/google/api/client/util/OpenCensusUtils.java, google-http-client/src/test/java/com/google/api/client/http/apache/ApacheHttpTransportTest.java, google-http-client/src/test/java/com/google/api/client/util/Base64Test.java, google-http-client/src/test/java/com/google/api/client/util/OpenCensusUtilsTest.java
Lint problems can be viewed in cl/192674895
=> internal: fix linting problems

google-http-client-android/src/main/java/com/google/api/client/extensions/android/json/AndroidJsonParser.java, google-http-client-gson/src/main/java/com/google/api/client/json/gson/GsonParser.java, google-http-client/src/main/java/com/google/api/client/util/Throwables.java, google-http-client/src/main/java/com/google/api/client/util/store/AbstractMemoryDataStore.java, google-http-client/src/main/java/com/google/api/client/util/store/FileDataStoreFactory.java, google-http-client/src/test/java/com/google/api/client/testing/http/MockHttpTransportTest.java, pom.xml
This lacks the linting fixes / jdk5->7 / datanucleus changes from https://github.com/google/google-http-java-client/pull/409.
=> Moe without linting

pom.xml
I intend on making the same change to oauth and api, but figured I'd just send out one CL for now in order to codereview phrasing in only one place (I will use this as a template for the other repos).
=> docs: document process for updating pom.xml versions

google-http-client-appengine/src/main/java/com/google/api/client/extensions/appengine/datastore/AppEngineDataStoreFactory.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/google-http-java-client/388)
=> Typo fix at AppEngineDataStoreFactory.Builder.build()

google-http-client/src/main/java/com/google/api/client/http/HttpStatusCodes.java
Added constant for STATUS_CODE_ACCEPTED in the HttpStatusCodes interface.
=> google-http-client: add STATUS_CODE_ACCEPTED to the list of status codes

google-http-client/src/main/java/com/google/api/client/util/ClassInfo.java
Fixes a error-prone-error when importing to internal repo.
=> Fix referential comparison of the two strings

google-http-client-jackson/pom.xml, google-http-client/pom.xml
=> Include Automatic-Module-Name in MANIFEST.MF

google-http-client-assembly/dependencies/google-http-client-appengine-dependencies.html, pom.xml
@chingor13 This is years out of date
=> update app engine SDK

google-http-client-jackson/pom.xml, pom.xml
@chingor13 Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
- [X ] Tests pass
Not sure how doc generation works here. I hope it's automatic and we don't need to check in generated code.
=> fix API doc links

pom.xml
Fixes #477 @chingor13 
- [ X] Tests pass
- [ X] Appropriate docs were updated (if necessary)
=> update test library versions

google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
=> Fix test to run on environments with German locale (#473)

.kokoro/release/common.cfg, .kokoro/release/common.sh, .kokoro/release/drop.cfg, .kokoro/release/drop.sh, .kokoro/release/promote.cfg, .kokoro/release/promote.sh, .kokoro/release/stage.cfg, .kokoro/release/stage.sh, google-http-client-android/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-jdo/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml
Adds Kokoro scripts to perform staging and release or drop.
=> Kokoro release jobs

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-jdo/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml, versions.txt
https://github.com/googleapis/releasetool will manage version bumping and help create the release PRs.
=> Enable releasetool for this project

google-http-client-android-test/pom.xml, google-http-client-android/pom.xml, google-http-client-appengine/pom.xml, google-http-client-assembly/pom.xml, google-http-client-findbugs/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, google-http-client-jackson2/pom.xml, google-http-client-jdo/pom.xml, google-http-client-protobuf/pom.xml, google-http-client-test/pom.xml, google-http-client-xml/pom.xml, google-http-client/pom.xml, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml, samples/googleplus-simple-cmdline-sample/pom.xml, versions.txt
=> Bump next snapshot

.kokoro/continuous/java11.cfg, .kokoro/presubmit/java11.cfg, README.md
=> Add Java 11 Kokoro config

pom.xml
=> Set the version of the jarjar-maven-plugin in pluginManagement

pom.xml
=> Upgrade maven-javadoc-plugin to 3.0.1

google-http-client-bom/README.md, google-http-client-bom/pom.xml, pom.xml, versions.txt
=> Add google-http-client-bom artifact

google-http-client-jdo/src/main/java/com/google/api/client/extensions/jdo/JdoDataStoreFactory.java
=> Deprecate JdoDataStoreFactory

google-http-client/src/main/java/com/google/api/client/http/HttpBackOffUnsuccessfulResponseHandler.java
=> Allow override on HttpBackOffUnsuccessfulResponseHandler#handleResponse

google-http-client/src/main/java/com/google/api/client/http/OpenCensusUtils.java
We are depending upon pre-1.0 apis from opencensus. We need to allow for
the possibility of needing to change the API here.
=> Annotation OpenCensusUtils as beta.

google-http-client-apache-legacy/src/main/java/com/google/api/client/http/apache/ApacheHttpResponse.java, google-http-client-apache-legacy/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java, google-http-client-apache-legacy/src/main/java/com/google/api/client/http/apache/ContentEntity.java, google-http-client-apache-legacy/src/main/java/com/google/api/client/http/apache/SSLSocketFactoryExtension.java, google-http-client-apache/src/main/java/com/google/api/client/http/apache/ContentEntity.java, google-http-client/src/main/java/com/google/api/client/http/HttpBackOffUnsuccessfulResponseHandler.java, google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/http/OpenCensusUtils.java, google-http-client/src/main/java/com/google/api/client/http/UriTemplate.java, google-http-client/src/main/java/com/google/api/client/util/FieldInfo.java, pom.xml, samples/dailymotion-simple-cmdline-sample/pom.xml
Various style suggestions from internal checkers
=> Code style cleanup

pom.xml
Upgrade surefire plugin to fix the build
=> Upgrade surefire plugin to fix the build

google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java, google-http-client/src/main/java/com/google/api/client/http/HttpResponse.java, google-http-client/src/test/java/com/google/api/client/http/HttpResponseTest.java
Fixes towards [#1009](https://github.com/googleapis/google-api-java-client/issues/1009)
=> Add option to return raw stream from response

.gitignore
@chingor13 
- [ X] Tests pass
- [ N/A] Appropriate docs were updated (if necessary)
=> ignore Mac Finder metadata

google-http-client-appengine/pom.xml
@sduskis At some point we'll need to push this to Java 8. 
- [ X] Tests pass
- [X ] Appropriate docs were updated (if necessary)
=> Update comment to match plugin configuration

pom.xml
=> remove duplicate version definition

google-http-client-apache-legacy/pom.xml, google-http-client-apache/pom.xml, google-http-client/pom.xml, samples/dailymotion-simple-cmdline-sample/instructions.html
- [X ] Tests pass
- [ X] Appropriate docs were updated (if necessary)
=> more fixes for Java 7 minimum version

google-http-client/src/test/java/com/google/api/client/util/DataTest.java
=> Added unit tests for null enum and unknown enum.

google-http-client/src/main/java/com/google/api/client/http/HttpHeaders.java, google-http-client/src/test/java/com/google/api/client/http/HttpHeadersTest.java
=> Added Warning header and unit tests.

google-http-client-findbugs/pom.xml
Upgrading findbugs fixes the issues in the precommit builds. @sduskis, @elharo, any issues with upgrading this dependency?
=> Fix build issue for findbugs module.

google-http-client/src/main/java/com/google/api/client/util/FieldInfo.java
=> avoid default locale

google-http-client-assembly/readme.html
and that's probably a good thing
@sduskis
=> .classpath no longer seems to exist

google-http-client-bom/pom.xml
=> remove assembly from BOM

pom.xml
=> fix up dependencies

.kokoro/release/publish_javadoc.cfg, .kokoro/release/publish_javadoc.sh, google-http-client-apache-legacy/pom.xml, google-http-client-bom/pom.xml, google-http-client-gson/pom.xml, google-http-client-jackson/pom.xml, pom.xml
Adds a kokoro job to publish javadocs to our new docs location.
=> Add publish javadoc kokoro job

google-http-client/src/main/java/com/google/api/client/http/apache/ApacheHttpRequest.java
The RequestConfig class is an API from the newer Apache HttpClient 4.5.x
clients.
This blocks our internal import code.
=> Restore the ApacheHttpRequest implementation.

google-http-client/src/main/java/com/google/api/client/http/HttpHeaders.java, google-http-client/src/main/java/com/google/api/client/util/Objects.java
Fixes found from internal linters.
* Fix javadoc param name
* Group overloads together
=> Linting cleanup

google-http-client/src/test/java/com/google/api/client/util/DataTest.java, google-http-client/src/test/java/com/google/api/client/util/TypesTest.java
Cleanup style found from internal linters
=> new ClassName().getClass() -> ClassName.class

pom.xml
=> Update to protobuf 3.9.1

google-http-client-bom/pom.xml
=> build: fix missing version warnings

.gitignore, README.md, docs/_config.yml, docs/_data/navigation.yml, docs/_layouts/default.html, docs/android.md, docs/component-modules.md, docs/exponential-backoff.md, docs/google-app-engine.md, docs/http-transport.md, docs/index.md, docs/json.md, docs/setup.md, docs/unit-testing.md
Once moved here, we can disable the wiki and enable GitHub pages from the root docs/ folder on master
=> docs: migrate docs into source control from the wiki

pom.xml
This might help with #820
@chanseokoh @chingor13
=> Latest apache httpcomponents and core

docs/setup.md
=> libraries-bom 2.6.0

google-http-client-assembly/classpath-include
@chingor13 we deleted this artifact a while back
=> Remove old jackson 1 reference

pom.xml
=> chore(deps): <project.guava.version>28.2-android</project.guava.version>

docs/setup.md
=> docs: libraries-bom 3.4.0

pom.xml
=> Update apache httpclient

docs/component-modules.md
=> fix: missing space

docs/setup.md
=> Latest BOM version

docs/setup.md
=> docs: bom 4.0.0

docs/setup.md
=> docs: libraries-bom 4.0.1

docs/setup.md
Released: https://search.maven.org/artifact/com.google.cloud/libraries-bom/4.1.0/pom
=> chore(docs): libraries-bom 4.1.0

docs/setup.md
=> docs: libraries-bom 4.1.1

pom.xml
This has a few bug fixes of note.
=> deps: httpclient 4.5.12

pom.xml
=> fix: add linkage monitor plugin

docs/index.md
=> docs: android 4.4 or later is required

docs/setup.md
=> chore(doc): libraries-bom 4.3.0

pom.xml
=> deps: update to Guava 29

docs/setup.md
=> chore: update libraries-bom to 5.5.0 

google-http-client-bom/pom.xml, pom.xml
=> ci: lock google-java-formatter version

docs/setup.md
=> chore(docs): libraries-bom 8.0.0

docs/json.md, samples/snippets/pom.xml, samples/snippets/src/main/java/com/example/json/YouTubeSample.java, samples/snippets/src/main/resources/youtube-search.json, samples/snippets/src/test/java/com/example/json/YouTubeSampleTest.java
=> samples: replace Google+ json example with YouTube example

docs/setup.md
=> docs: BOM 8.1.0

docs/setup.md
=> docs: update libraries-bom

pom.xml
=> deps: update protobuf-java

docs/setup.md
@elharo @chingor13 Would you check and merge this PR?
=> docs: libraries-bom 10.0.0

docs/setup.md
=> BOM 10.1.0

docs/setup.md
=> docs: libaries-bom 11.0.0

docs/setup.md
=> docs: libraries-bom 12.1.0

pom.xml
=> deps: guava 30.0-android

docs/setup.md
@elharo @chingor13 Can you review this?
=> chore: libraries-bom 13.3.0

docs/setup.md
=> chore: libraries-bom 13.4.0

docs/setup.md
=> docs: BOM 15.0.0

docs/setup.md
=> chore: libraries-bom 16.1.0

docs/setup.md
=> chore(docs): add gradle instructions to setup.md

pom.xml
=> deps: update guava to 30.1-android

docs/setup.md
=> docs: libraries-bom 16.2.0

docs/setup.md
=> chore(deps): libraries BOM 16.2.1

docs/setup.md
@elharo @chingor13 Would you check this? (Feel free to merge this when you approve)
=> chore(deps): libraries-bom 16.3.0

docs/setup.md
=> docs: libraries-bom 16.4.0

google-http-client-jackson2/pom.xml, pom.xml
@chingor13 This fixes some CI failures
=> docs: jackson does not maintain stable Javadocs

docs/setup.md
The Libraries BOM 17.0.0 is released.
https://search.maven.org/artifact/com.google.cloud/libraries-bom/17.0.0/pom
---
=> chore(deps): libraries BOM 17.0.0

docs/setup.md
=> chore(deps): libraries-bom 18.0.0

google-http-client-bom/README.md
=> docs: update version

samples/snippets/pom.xml, samples/snippets/src/main/java/com/example/json/YouTubeSample.java, samples/snippets/src/test/java/com/example/json/YouTubeSampleTest.java
=> chore: fix build warnings

README.md
=> chore: update README with CI, stability, latest version badges

docs/setup.md
=> docs: 19.0.0 libraries-bom

docs/setup.md
=> chore(deps): libraries BOM 19.1.0

docs/setup.md
=> chore(deps): libraries-bom 19.2.1

pom.xml
=> deps: update Guava patch

google-http-client-protobuf/pom.xml, pom.xml
@chingor13 @stephaniewang526 unbreaks build
=> fix: update protoc plugin

.github/release-please.yml, .github/sync-repo-settings.yaml
=> build: configure branch 1.39.2-sp as a release branch

docs/setup.md
=> chore(docs): libraries-bom 20.2.0

.github/workflows/ci.yaml, google-http-client-protobuf/pom.xml, pom.xml
=> feat: configure initial sp version

docs/setup.md
=> docs: bom 20.3.0

google-http-client/src/test/java/com/google/api/client/http/HttpRequestTest.java
=> test: relax test to allow sp versions

docs/setup.md
=> docs: com.google.cloud:libraries-bom:20.7.0

docs/setup.md
=> chore(deps): libraries-bom 20.8.0

docs/setup.md
=> docs: libraries-bom 20.9.0

docs/setup.md
Libraries BOM 21.0.0.
CC: @Neenu1995
=> chore(deps): libraries-bom 21.0.0

docs/setup.md
Updating document for the Libraries BOM 23.1.0
=> chore(deps): libraries-bom 23.1.0

docs/setup.md
Libraries BOM 24.0.0 release documentation update.
=> chore(deps): libraries-bom 24.0.0 release

docs/setup.md
=> chore(docs): libraries-bom 24.1.0

docs/setup.md
Updates the libraries-bom version referenced in docs.
=> chore(docs): libraries-bom 24.1.1

docs/setup.md
=> docs(deps): libraries-bom 24.4.0 release in google-http-java-client

google-http-client/src/main/java/com/google/api/client/http/HttpMediaType.java, google-http-client/src/test/java/com/google/api/client/http/HttpRequestTracingTest.java
=> chore: fix link in doc

pom.xml
Reverts googleapis/google-http-java-client#1621
=> deps: revert dependency com.google.protobuf:protobuf-java to v3.19.4

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 1.42.0

pom.xml
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
=> deps: downgrade appengine to 1.9.X

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 1.43.0

.github/workflows/scorecard.yml
=> ci: setting up OSSF Scorecard workflow

.github/release-please.yml, .github/sync-repo-settings.yaml
enable releases
```
release-brancher create-pull-request \
--branch-name="1.43.x" \
--target-tag="v1.43.3" \
--repo="googleapis/google-http-java-client" \
--pull-request-title="feat: setup 1.43.x lts branch" \
--release-type=java-backport
```
=> feat: setup 1.43.x lts branch

.kokoro/build.sh, .kokoro/presubmit/graalvm-native-a.cfg, .kokoro/presubmit/graalvm-native-b.cfg, owlbot.py
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
=> build: add native image kokoro cfgs

CONTRIBUTING.md, owlbot.py
Updating CONTRIBUTING.md as per go/java-repos-contrib-guidelines
b/323273913
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
=> chore: updating CONTRIBUTING.md

.kokoro/presubmit/graalvm-native-a.cfg, .kokoro/presubmit/graalvm-native-b.cfg, pom.xml
renovate bot have not created and dashboard not moving.
Manually create upgrade.
If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).
=> deps: update dependency com.google.cloud:native-image-shared-config to v1.9.0

renovate.json
Reverts googleapis/google-http-java-client#1968
=> Revert "chore: Limit guava version to v30"

google-http-client-bom/pom.xml
=> fix: add google-http-client-apache-v5 to bom

pom.xml
Reverts googleapis/google-http-java-client#2068
=> Revert "deps: update dependency io.grpc:grpc-context to v1.70.0"

pom.xml
This is to align all grpc version for LTS
=> deps: update grpc-context to 1.70.0

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 1.47.0

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 1.48.0
